# This rule is not used by the project k8s-backup-dr-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over backup.manuchim.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-backup-dr-operator
    app.kubernetes.io/managed-by: kustomize
  name: backup-admin-role
rules:
- apiGroups:
  - backup.manuchim.dev
  resources:
  - backups
  verbs:
  - '*'
- apiGroups:
  - backup.manuchim.dev
  resources:
  - backups/status
  verbs:
  - get
