# This rule is not used by the project k8s-backup-dr-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to backup.manuchim.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-backup-dr-operator
    app.kubernetes.io/managed-by: kustomize
  name: backuppolicy-viewer-role
rules:
- apiGroups:
  - backup.manuchim.dev
  resources:
  - backuppolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.manuchim.dev
  resources:
  - backuppolicies/status
  verbs:
  - get
