apiVersion: backup.manuchim.dev/v1alpha1
kind: Backup
metadata:
  labels:
    app.kubernetes.io/name: k8s-backup-dr-operator
    app.kubernetes.io/managed-by: kustomize
  name: backup-sample
spec:
  # TODO(user): Add fields here
